export enum LearningEventType {
  SESSION_STARTED = 'SESSION_STARTED',
  SESSION_PAUSED = 'SESSION_PAUSED',
  SESSION_RESUMED = 'SESSION_RESUMED',
  SESSION_COMPLETED = 'SESSION_COMPLETED',
  SESSION_CANCELLED = 'SESSION_CANCELLED',
  TOPIC_STARTED = 'TOPIC_STARTED',
  TOPIC_COMPLETED = 'TOPIC_COMPLETED',
  TOPIC_SKIPPED = 'TOPIC_SKIPPED',
  ACTIVITY_STARTED = 'ACTIVITY_STARTED',
  ACTIVITY_COMPLETED = 'ACTIVITY_COMPLETED',
  ACTIVITY_SKIPPED = 'ACTIVITY_SKIPPED',
  ACTIVITY_FAILED = 'ACTIVITY_FAILED',
  VIDEO_COMPLETED = 'VIDEO_COMPLETED',
  AUDIO_COMPLETED = 'AUDIO_COMPLETED',
  SPEECH_COMPLETED = 'SPEECH_COMPLETED',
  WRITING_COMPLETED = 'WRITING_COMPLETED',
  RECOVERY_STARTED = 'RECOVERY_STARTED',
  RECOVERY_COMPLETED = 'RECOVERY_COMPLETED',
  DAILY_PRACTICE_COMPLETED = 'DAILY_PRACTICE_COMPLETED',
  MASTERY_PRACTICE_COMPLETED = 'MASTERY_PRACTICE_COMPLETED',
  REINFORCEMENT_COMPLETED = 'REINFORCEMENT_COMPLETED',
}

export enum Modality {
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  SPEECH = 'SPEECH',
  WRITING = 'WRITING',
  GAME = 'GAME',
  STORY = 'STORY',
  MOTOR = 'MOTOR',
  CREATIVE = 'CREATIVE',
  WARMUP = 'WARMUP',
  REWARD = 'REWARD',
}

export enum EvidenceType {
  ATTEMPTS = 'ATTEMPTS',
  RETRIES = 'RETRIES',
  ACCURACY = 'ACCURACY',
  COMPLETION = 'COMPLETION',
  DURATION = 'DURATION',
  HINT_USAGE = 'HINT_USAGE',
  HELP_REQUESTS = 'HELP_REQUESTS',
  ENGAGEMENT = 'ENGAGEMENT',
  CONFIDENCE = 'CONFIDENCE',
}

export const VALID_MODALITIES = Object.values(Modality);
export const VALID_EVENT_TYPES = Object.values(LearningEventType);
export const VALID_EVIDENCE_TYPES = Object.values(EvidenceType);