export enum EvidenceType {
  COMPLETION = 'COMPLETION',
  MASTERY = 'MASTERY',
  RETENTION = 'RETENTION',
  CONFIDENCE = 'CONFIDENCE',
  ENGAGEMENT = 'ENGAGEMENT',
  DIFFICULTY = 'DIFFICULTY',
  SPEED = 'SPEED',
  ATTEMPT = 'ATTEMPT',
}
